var ie6_warning=navigator.userAgent.indexOf('MSIE 6')
if (ie6_warning > 0)
{
	document.write("<div  style='background:url(templates/fly/images/ie/ie_bg.gif) repeat-x left top; height:84px; text-align: center; clear: both; height: 84px; position: relative; z-index:5000'> <div style='position: absolute; right: 3px; top: 3px; font-family: courier new; font-weight: bold;'><a href='#' onclick='javascript:this.parentNode.parentNode.style.display=\"none\"; return false;'><img src='templates/fly/images/ie/close.gif' style='border: none;' alt='Close this notice'/></a></div> <div style='width: 870px; margin: 0 auto; text-align: left; padding: 0; overflow: hidden; color: black;'> <div style='width: 75px; float: left;'><img src='templates/fly/images/ie/warning.gif' alt='Warning!'/></div> <div style='width: 380px; float: left; font-family: Arial, sans-serif; color:#000'> <div style='font-size: 14px; font-weight: bold; margin: 20px 15px 0 15px; color:#000'>The browser you arke currently using is outdated.</div> <div style='font-size: 12px; margin-top: 6px; line-height: 12px; color:#000; width:250px;margin-left:15px'>Please, upgrade to a modern web browser for using this site in a better way.</div> </div><div style='float: left;'><a href='http://www.opera.com/' target='_blank'><img src='templates/fly/images/ie/opera.gif' style='border: none;' alt='Opera'/></a></div><div style='float: left; width: 73px;'><a href='http://www.google.com/chrome' target='_blank'><img src='templates/fly/images/ie/ghrome.gif' style='border: none;' alt='Get Google Chrome'/></a></div><div style='width: 75px; float: left;'><a href='http://www.firefox.com' target='_blank'><img src='templates/fly/images/ie/firefox.gif' style='border: none;' alt='Get Firefox 3.5'/></a></div><div style='width: 75px; float: left;'><a href='http://www.browserforthebetter.com/download.html' target='_blank'><img src='templates/fly/images/ie/ie8.gif' style='border: none;' alt='Get Internet Explorer 8'/></a></div> <div style='width: 73px; float: left;'><a href='http://www.apple.com/safari/download/' target='_blank'><img src='templates/fly/images/ie/safari.gif' style='border: none;' alt='Get Safari 4'/></a></div>  </div></div><style> .level0 {border:0px solid #0062C7;}</style>" );}
	
	

var ie7_warning=navigator.userAgent.indexOf('MSIE 7')
if (ie7_warning > 0)
{
	document.write("<div  style='background:url(templates/fly/images/ie/ie_bg.gif) repeat-x left top; height:84px; text-align: center; clear: both; height: 84px; position: relative; z-index:5000'> <div style='position: absolute; right: 3px; top: 3px; font-family: courier new; font-weight: bold;'><a href='#' onclick='javascript:this.parentNode.parentNode.style.display=\"none\"; return false;'><img src='templates/fly/images/ie/close.gif' style='border: none;' alt='Close this notice'/></a></div> <div style='width: 870px; margin: 0 auto; text-align: left; padding: 0; overflow: hidden; color: black;'> <div style='width: 75px; float: left;'><img src='templates/fly/images/ie/warning.gif' alt='Warning!'/></div> <div style='width: 380px; float: left; font-family: Arial, sans-serif; color:#000'> <div style='font-size: 14px; font-weight: bold; margin: 20px 15px 0 15px; color:#000'>The browser you arke currently using is outdated.</div> <div style='font-size: 12px; margin-top: 6px; line-height: 12px; color:#000; width:250px;margin-left:15px'>Please, upgrade to a modern web browser for using this site in a better way.</div> </div><div style='float: left;'><a href='http://www.opera.com/' target='_blank'><img src='templates/fly/images/ie/opera.gif' style='border: none;' alt='Opera'/></a></div><div style='float: left; width: 73px;'><a href='http://www.google.com/chrome' target='_blank'><img src='templates/fly/images/ie/ghrome.gif' style='border: none;' alt='Get Google Chrome'/></a></div><div style='width: 75px; float: left;'><a href='http://www.firefox.com' target='_blank'><img src='templates/fly/images/ie/firefox.gif' style='border: none;' alt='Get Firefox 3.5'/></a></div><div style='width: 75px; float: left;'><a href='http://www.browserforthebetter.com/download.html' target='_blank'><img src='templates/fly/images/ie/ie8.gif' style='border: none;' alt='Get Internet Explorer 8'/></a></div> <div style='width: 73px; float: left;'><a href='http://www.apple.com/safari/download/' target='_blank'><img src='templates/fly/images/ie/safari.gif' style='border: none;' alt='Get Safari 4'/></a></div>  </div></div><style> .level0 {border:0px solid #0062C7;}</style>" );}